NeighborhoodWeatherCommunityApp/weather

back/src/main/java/org/pknu/weather/domain/Location.java
back/src/main/java/org/pknu/weather/domain/Member.java
back/src/main/java/org/pknu/weather/domain/Post.java
back/src/main/java/org/pknu/weather/domain/Recommendation.java
back/src/main/java/org/pknu/weather/domain/Tag.java
back/src/main/java/org/pknu/weather/domain/Weather.java
back/src/main/java/org/pknu/weather/domain/common/RainType.java
back/src/main/java/org/pknu/weather/domain/common/Sensitivity.java
back/src/main/java/org/pknu/weather/domain/common/SkyType.java

[refactor] 패키지 구조를 변경합니다.

---

front/.gitignore

[chore] .gitignore 파일 수정

---

front/src/screens/HomeScreen.js

[feat] 일정 거리 이상(translationX > 200) 오른쪽으로 스와이프 시 화면 전환

---

front/src/components/AirQuality.js
front/src/components/CurrentLocation.js
front/src/components/HourlyForecast.js
front/src/components/PostButton.js
front/src/components/PostSlider.js
front/src/components/Posts.js
front/src/components/TemperatureInfo.js
front/src/components/ToggleViewButton.js
front/src/components/WeatherInfoSlider.js
front/src/screens/HomeScreen.js

[feat] 메인 화면을 구성하는 HomeScreen의 하위 컴포넌트 구현

---

front/src/components/WeatherGraph.js
front/src/screens/HomeScreen.js

[feat] SVG로 시간에 따른 온도 변화 그래프 렌더링

---

front/src/screens/MyScreen.js

[feat] My 화면 구성요소 배치

---

front/src/components/Posts.js

- 메인 화면 배너 UI 개선
- '자세하게 공유하기' 및 '간단하게 공유하기' 버튼 추가
-

[feat] 컴포넌트 마운트 시, 첫 번째 게시물 뷰를 기본으로 설정

---

back/build.gradle
back/src/main/resources/application.yml

[BE] health check 설정 추가

---

.github/workflows/gradle.yml
back/build.gradle
back/src/main/java/org/pknu/weather/repository/WeatherRepository.java
back/src/main/resources/application.yml
back/src/test/java/org/pknu/weather/service/WeatherServiceTest.java

- #39
```
[2024-08-19 05:35:45:11592]  INFO  1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
[2024-08-19 05:35:45:11784]  DEBUG 1 --- [           main] com.zaxxer.hikari.pool.PoolBase          : HikariPool-1 - Failed to create/setup connection: Communications link failure
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[2024-08-19 05:35:45:11784]  DEBUG 1 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Cannot acquire connection from data source
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any …
```

[fix] Could not open JPA EntityManager for transaction 해결중

---

front/src/components/PostScroll.js
front/src/components/WeatherShareButton.js
front/src/screens/CommunityScreen.js

[[FE] Community 탭 UI 설계 #52](https://github.com/NeighborhoodWeatherCommunityApp/weather/issues/52)
- newPosts 배열 렌더링 시, Math.random()으로 인한 key 중복 문제 해결을 위해
page, index, Date.now()를 결합하여 고유한 키를 생성합니다.

[feat] Community 탭의 newPosts 배열 무한 스크롤 구현

---

.github/workflows/gradle.yml

[BE/Feat] Kakao oauth 어세스 토큰 및 앱 jwt 토큰 구현

---

back/src/main/java/org/pknu/weather/config/FilterConfig.java

- 깃허브 액션 실행 용 커밋으로 수정사항 없습니다.
- 깃허브 액션 실행 옵션을 보니 back폴더에 수정이 없으면 액션이 실행되지 않은 것 같아 /n을 하나만 제거해서 PR을 다시 날립니다.
-

[BE/Bug] 깃허브 액션 실행 용 커밋 - 수정사항 없음

---

back/src/main/java/org/pknu/weather/apiPayload/code/status/ErrorStatus.java
back/src/main/java/org/pknu/weather/common/TokenConverter.java
back/src/main/java/org/pknu/weather/controller/LocationControllerV1.java
back/src/main/java/org/pknu/weather/domain/Member.java
back/src/main/java/org/pknu/weather/security/util/JWTUtil.java
back/src/main/java/org/pknu/weather/service/LocationService.java

- #72 
- 나중에 작성 예정
- 나중에 작성 예정

[BE/Feat] 유저의 기본 주소 조회 API 및 지역 정보를 저장할 때 멤버의 기본 장소로 설정하도록 수정

---

back/src/main/resources/application.yml

[BE/Bug] 로그 생성 파일 경로 설정 변경

---

.github/workflows/cd.yml
.github/workflows/ci.yml
.github/workflows/test.yml

[BE/Config] CI/CD워크플로 파일  수정

---

.github/workflows/gradle.yml
back/src/main/java/org/pknu/weather/common/DateTimeFormaterUtils.java

[BE/Fix] post 조회시 생성 시각이 음수로 반환되는 현상 수정

---

front/App.js
front/ios/Weather2/Info.plist
front/src/api/api.js
front/src/components/TemperatureInfo.js
front/src/screens/LoginScreen.js
front/src/screens/MyScreen.js

- 최초 로그인 테스트를 위해 임의로 isNewMember 값을 true로 설정
-

[FE/Feat] AppToken 발급 API 연동

---

back/src/main/java/org/pknu/weather/common/ApplicationStartupListener.java
back/src/main/java/org/pknu/weather/common/SgisLocationUtils.java
back/src/main/java/org/pknu/weather/common/TokenConverter.java
back/src/main/java/org/pknu/weather/common/feignClient/dto/SgisLocationResponseDTO.java
back/src/main/java/org/pknu/weather/controller/LocationControllerV1.java
back/src/main/java/org/pknu/weather/domain/Location.java
back/src/main/java/org/pknu/weather/dto/LocationDTO.java
back/src/main/java/org/pknu/weather/dto/converter/LocationConverter.java
back/src/main/java/org/pknu/weather/service/LocationService.java
back/src/main/resources/application.yml

[BE/Bug]사용자의 어세스 토큰에서 이메일을 가져오도록 하는 스태틱 메서드 생성

---

back/src/main/java/org/pknu/weather/controller/CommunityControllerV1.java
back/src/main/java/org/pknu/weather/controller/MainPageControllerV1.java
back/src/main/java/org/pknu/weather/controller/PostControllerV1.java
back/src/main/java/org/pknu/weather/dto/PostResponse.java
back/src/main/java/org/pknu/weather/dto/converter/PostResponseConverter.java
back/src/main/java/org/pknu/weather/repository/PostCustomRepository.java
back/src/main/java/org/pknu/weather/repository/PostCustomRepositoryImpl.java
back/src/main/java/org/pknu/weather/service/MainPageService.java
back/src/main/java/org/pknu/weather/service/PostQueryService.java
back/src/test/java/org/pknu/weather/common/DateTimeFormatterTest.java
back/src/test/java/org/pknu/weather/repository/PostRepositoryTest.java
back/src/test/java/org/pknu/weather/service/PostQueryServiceTest.java
back/src/test/java/org/pknu/weather/service/PostServiceTest.java

[BE/Feat] 지역에서 좋아요를 가장 많이 받은 게시글 조회 API

---

back/src/main/java/org/pknu/weather/apiPayload/ApiResponse.java
back/src/main/java/org/pknu/weather/apiPayload/code/status/ErrorStatus.java
back/src/main/java/org/pknu/weather/controller/PostControllerV1.java
back/src/main/java/org/pknu/weather/repository/PostRepository.java
back/src/main/java/org/pknu/weather/repository/RecommendationCustomRepository.java
back/src/main/java/org/pknu/weather/repository/RecommendationCustomRepositoryImpl.java
back/src/main/java/org/pknu/weather/repository/RecommendationRepository.java
back/src/main/java/org/pknu/weather/service/PostService.java
back/src/main/java/org/pknu/weather/validation/annotation/IsPositive.java
back/src/main/java/org/pknu/weather/validation/validator/PostExistValidator.java

- #101 
- 커스텀 어노테이션, 관련 클래스 생성(파라미터로 넘어오는 Id 검증)
- 좋아요 `취소` 기능이 없다는 가정하에 제작
-

[BE/Feat] 게시글 좋아요 기능 API

---

front/App.js
front/src/api/api.js
front/src/screens/PostCreationScreen.js

- 사용자는 "온도", "날씨", "습도", "바람", "먼지" 각각의 정보에 대해 하나의 태그를 선택합니다.
- 각 태그에 고유 코드를 지정하여 백엔드로 전달합니다.
-

[FE/Feat] 날씨 공유 API 연동

---

back/src/main/java/org/pknu/weather/dto/PostRequest.java

[BE/Fix] 검증 값 수정

---

front/android/app/src/main/AndroidManifest.xml
front/android/app/src/main/res/values/strings.xml
front/src/api/api.js
front/src/components/TemperatureInfo.js
front/src/screens/LoginScreen.js
front/src/screens/PostCreationScreen.js

- AndroidManifest.xml 파일 수정
- root 및 android/app 에서 각 위치의 키 해시를 모두 등록하였습니다.
-

[FE/Fix] Android 의존성 문제 해결

---

back/src/main/java/org/pknu/weather/apiPayload/code/status/ErrorStatus.java
back/src/main/java/org/pknu/weather/controller/MemberControllerV1.java
back/src/main/java/org/pknu/weather/domain/Member.java
back/src/main/java/org/pknu/weather/repository/MemberRepository.java
back/src/main/java/org/pknu/weather/service/MemberService.java

[BE/Fix]Member 정보 변경 시, null 값 확인 후 멤버 저장

---

front/android/app/src/main/AndroidManifest.xml
front/src/api/api.js
front/src/components/CurrentLocation.js
front/src/screens/HomeScreen.js

- Android 위치 권한 설정
- 플랫폼에 따라 위도, 경도 좌표 받아오는 로직 작성
-

[FE/Feat] Android 사용자의 대표 주소 설정 API 연동

---

back/src/main/java/org/pknu/weather/controller/CommunityControllerV1.java
back/src/main/java/org/pknu/weather/dto/converter/PostResponseConverter.java

[BE/Fix] 게시글 불러오기 API default value 에러나는 현상 수정 

---

front/src/api/api.js
front/src/components/PostScroll.js
front/src/components/WeatherInfoSlider.js
front/src/screens/HomeScreen.js

- PostScroll 컴포넌트에서 게시글 6개씩 조회 후, lastPostId를 통해 추가적으로 렌더링하도록 구현
- WeatherInfoSlider 컴포넌트에서 map() 함수로 렌더링 시 고유한 키 값을 사용하도록 수정
-

[fix] 게시글 조회 시 lastPostId를 통해 추가 조회하도록 수정

---

back/src/main/java/org/pknu/weather/common/GlobalParams.java
back/src/main/java/org/pknu/weather/common/utils/QueryUtils.java
back/src/main/java/org/pknu/weather/controller/MainPageControllerV1.java
back/src/main/java/org/pknu/weather/dto/WeatherQueryResult.java
back/src/main/java/org/pknu/weather/dto/WeatherResponse.java
back/src/main/java/org/pknu/weather/dto/converter/WeatherConverter.java
back/src/main/java/org/pknu/weather/dto/converter/WeatherResponseConverter.java
back/src/main/java/org/pknu/weather/repository/LocationCustomRepository.java
back/src/main/java/org/pknu/weather/repository/LocationCustomRepositoryImpl.java
back/src/main/java/org/pknu/weather/repository/WeatherCustomRepository.java
back/src/main/java/org/pknu/weather/repository/WeatherCustomRepositoryImpl.java
back/src/main/java/org/pknu/weather/service/MainPageService.java
back/src/main/java/org/pknu/weather/service/WeatherQueryService.java
back/src/test/java/org/pknu/weather/repository/WeatherRepositoryTest.java

[BE/Feat] 간단 날씨 정보 - 강수 정보 조회 API 구현

---

front/src/api/api.js
front/src/components/InterestItem.js
front/src/screens/InterestScreen.js

- 사용자의 대표 주소를 조회하여 위치 정보를 보여줍니다.
- 텍스트 클릭 시, 위치 정보를 직접 검색하여 수정할 수 있는 모달창을 생성합니다.
-

[FE/Feat] 취미탭 위치 정보 수정 기능 구현

---

back/src/main/java/org/pknu/weather/controller/MainPageControllerV1.java
back/src/main/java/org/pknu/weather/dto/WeatherResponse.java
back/src/main/java/org/pknu/weather/dto/converter/WeatherResponseConverter.java
back/src/test/java/org/pknu/weather/common/TestDataCreator.java

[BE/Fix] /api/v1/main/weather 응답값 일부 수정

---

back/src/main/java/org/pknu/weather/domain/Post.java
back/src/main/java/org/pknu/weather/domain/common/PostType.java

- #148 
- 각 커뮤니티 글의 구분을 위해 게시글에 타입을 추가했습니다.
- 날씨 커뮤니티: weather
- 런닝 커뮤니티: run
- 등산 커뮤니티: hiking
- 반려동물 산책 커뮤니티: pet
- 각각의 게시물은 위의 4개중 하나의 타입을 가지며 weather 타입은 메인 화면인 날씨 커뮤니티를 위해 사용되며, 기본값으로 설정했습니다.

[BE/Fix] postType 추가

---

front/src/api/api.js
front/src/components/AirQuality.js
front/src/components/CurrentLocation.js
front/src/components/HourlyForecast.js
front/src/components/InterestItem.js
front/src/components/Posts.js
front/src/components/TemperatureInfo.js
front/src/components/ToggleViewButton.js
front/src/screens/CommunityScreen.js
front/src/screens/HomeScreen.js
front/src/screens/InterestScreen.js

- 초미세먼지, 미세먼지, 자외선, 오존 데이터를 조회합니다.
-

[FE/Feat] 기타 날씨 정보 조회 API 연동

---

front/App.js
front/src/api/api.js
front/src/components/CurrentLocation.js
front/src/components/InterestItem.js
front/src/components/InterestPostScroll.js
front/src/screens/InterestPostCreationScreen.js
front/src/screens/InterestScreen.js
front/src/screens/LoginScreen.js
front/src/screens/MyScreen.js
front/src/screens/RegisterProfileScreen.js

- 카카오 로그인 성공 및 회원 정보 입력 후, Home 화면으로 이동 전 동작합니다.
- 위도, 경도 좌표를 받아와 대표 주소를 설정합니다.
-

[FE/Fix] 대표 주소 설정 로직 수정

---

back/src/main/java/org/pknu/weather/common/utils/TagUtils.java
back/src/main/java/org/pknu/weather/dto/WeatherResponse.java
back/src/main/java/org/pknu/weather/dto/converter/WeatherResponseConverter.java

[BE/Refactor] 간단 날씨 보기 API 들의 응답값 수정

---

front/android/app/build.gradle
front/android/app/src/main/AndroidManifest.xml
front/package-lock.json
front/package.json
front/src/components/KakaoShareButton.js
front/src/screens/HomeScreen.js
front/src/screens/MyScreen.js

[feat] 카카오 SDK를 통한 날씨 정보 공유 로직 작성

---

back/src/main/java/org/pknu/weather/apiPayload/code/status/ErrorStatus.java
back/src/main/java/org/pknu/weather/controller/CommunityControllerV1.java
back/src/main/java/org/pknu/weather/controller/PostControllerV1.java
back/src/main/java/org/pknu/weather/domain/Post.java
back/src/main/java/org/pknu/weather/domain/common/PostType.java
back/src/main/java/org/pknu/weather/domain/tag/SkyTag.java
back/src/main/java/org/pknu/weather/dto/PostRequest.java
back/src/main/java/org/pknu/weather/dto/converter/PostConverter.java
back/src/main/java/org/pknu/weather/repository/PostCustomRepository.java
back/src/main/java/org/pknu/weather/repository/PostCustomRepositoryImpl.java
back/src/main/java/org/pknu/weather/service/PostQueryService.java
back/src/main/java/org/pknu/weather/service/PostService.java
back/src/test/java/org/pknu/weather/common/Dummy.java
back/src/test/java/org/pknu/weather/common/TestDataCreator.java
back/src/test/java/org/pknu/weather/service/PostQueryServiceTest.java
back/src/test/java/org/pknu/weather/service/PostServiceTest.java

- #159
- 글 조회하기 API는 기존의 API에 파라미터만 추가
- 글 쓰기 API는 따로 생성하였습니다.
-

[BE/Refactor] 취미탭 글 쓰기, 조회하기 API 구현

---

front/App.js
front/src/api/api.js
front/src/screens/InterestPostCreationScreen.js
front/src/screens/MyScreen.js
front/src/screens/PostCreationScreen.js

[FE/Feat] 취미탭 게시글 작성 API 연동

---

front/android/app/src/main/AndroidManifest.xml
front/src/api/api.js
front/src/components/AirQuality.js
front/src/components/InterestItem.js
front/src/components/Posts.js
front/src/screens/LoginScreen.js
front/src/screens/MyScreen.js
front/src/screens/RegisterProfileScreen.js

[FE/Fix] 회원 정보 입력 로직 수정

---

back/src/main/java/org/pknu/weather/apiPayload/code/status/ErrorStatus.java
back/src/main/java/org/pknu/weather/common/utils/AddressFinder.java
back/src/main/java/org/pknu/weather/controller/LocationControllerV1.java
back/src/main/java/org/pknu/weather/service/LocationService.java
back/src/test/java/org/pknu/weather/repository/LocationCodeRepositoryTest.java

- #156 
- 취미탭에서 사용자가 주소를 변경할 경우 사용할 api 구현

[BE/Feat] 주소 검색 API 구현

---

front/src/components/InterestItem.js
front/src/screens/CommunityScreen.js

[FE/Feat] 주소 검색 API 연동

---

back/src/test/java/org/pknu/weather/repository/LocationCodeRepositoryTest.java

[BE/Fix]테스트 주석 처리

---

back/src/main/java/org/pknu/weather/apiPayload/code/status/ErrorStatus.java
back/src/main/java/org/pknu/weather/common/utils/SgisLocationUtils.java
back/src/main/java/org/pknu/weather/controller/LocationControllerV1.java
back/src/main/java/org/pknu/weather/service/LocationService.java

- #171 
- 브랜치를 착각해서 해당 브랜치로 푸쉬합니다.
- 주소의 도/시군수/읍면동 정보를 입력하면 주소 엔티티를 생성합니다.

[BE/FEAT]  주소 생성 API 작성

---

front/src/api/api.js
front/src/components/InterestItem.js

[FE/Feat] 주소 생성 API 연동

---

front/App.js
front/src/api/api.js
front/src/components/CurrentLocation.js
front/src/components/HourlyForecast.js
front/src/components/InterestItem.js
front/src/components/InterestPostScroll.js
front/src/components/KakaoShareButton.js
front/src/components/PostScroll.js
front/src/components/Posts.js
front/src/components/TemperatureInfo.js
front/src/components/WeatherGraph.js
front/src/components/WeatherInfoSlider.js
front/src/screens/CommunityScreen.js
front/src/screens/HomeScreen.js
front/src/screens/InterestPostCreationScreen.js
front/src/screens/InterestScreen.js
front/src/screens/PostCreationScreen.js
front/src/screens/RegisterProfileScreen.js

[FE/Fix] memberId 파라미터 제거

---

front/App.js
front/src/components/AirQuality.js
front/src/components/CurrentLocation.js
front/src/components/HourlyForecast.js
front/src/components/InterestItem.js
front/src/components/InterestPostScroll.js
front/src/components/KakaoShareButton.js
front/src/components/Posts.js
front/src/components/TemperatureInfo.js
front/src/components/WeatherInfoSlider.js
front/src/components/WeatherShareButton.js
front/src/screens/CommunityScreen.js
front/src/screens/HomeScreen.js
front/src/screens/InterestPostCreationScreen.js
front/src/screens/InterestScreen.js
front/src/screens/MyScreen.js
front/src/screens/PostCreationScreen.js

[FE/Refactor] 기기별 세부 UI 최적화

---

front/App.js
front/src/components/InterestItem.js
front/src/components/InterestPostScroll.js
front/src/components/PostScroll.js
front/src/components/Posts.js
front/src/screens/InterestScreen.js
front/src/screens/MyScreen.js
front/src/screens/RegisterProfileScreen.js

- likeClickable 상태에 따른 좋아요 아이콘 색상 수정
- 하단 탭 바 아이콘 사이즈 및 padding 수정
-

[FE/Refactor] 아이콘 관련 UI 최적화

---

back/src/main/java/org/pknu/weather/dto/LocationDTO.java
back/src/main/java/org/pknu/weather/dto/converter/LocationConverter.java

- #172 
- 주소를 생성하고 응답하는 결과 값에 주소의 id를 추가합니다.

[BE/Fix]주소 생성의 응답에 주소 id 추가

---

back/src/main/java/org/pknu/weather/controller/LocationControllerV1.java
back/src/main/java/org/pknu/weather/service/LocationService.java

- #182 
- 사용자가 자신의 기본 주소 설정 시 응답 값에 locationId를 추가했습니다.
- 기본 지역생성 API를 생성했습니다.
- 기본 지역이란 현재 사용하고 있는 sigs 지오코딩 서비스에서 처리하지 못하는 지역입니다.

[BE/FIX] : 사용자의 기본 주소 설정 응답 값 location id 추가 및 기본 지역 생성 API 추가

---

back/src/main/java/org/pknu/weather/aop/LocationCheckAspect.java
back/src/main/java/org/pknu/weather/common/utils/RecommendationUtils.java
back/src/main/java/org/pknu/weather/controller/CommunityControllerV1.java
back/src/main/java/org/pknu/weather/controller/MainPageControllerV1.java
back/src/main/java/org/pknu/weather/controller/MemberControllerV1.java
back/src/main/java/org/pknu/weather/controller/PostControllerV1.java
back/src/main/java/org/pknu/weather/dto/PostResponse.java
back/src/main/java/org/pknu/weather/repository/MemberRepository.java
back/src/main/java/org/pknu/weather/repository/RecommendationRepository.java
back/src/main/java/org/pknu/weather/service/MainPageService.java
back/src/main/java/org/pknu/weather/service/MemberQueryService.java
back/src/main/java/org/pknu/weather/service/PostQueryService.java
back/src/main/java/org/pknu/weather/service/PostService.java
back/src/main/java/org/pknu/weather/service/TagQueryService.java
back/src/main/java/org/pknu/weather/service/WeatherQueryService.java
back/src/main/java/org/pknu/weather/service/WeatherService.java
back/src/test/java/org/pknu/weather/aop/AspectTest.java
back/src/test/java/org/pknu/weather/common/TestDataCreator.java
back/src/test/java/org/pknu/weather/service/PostQueryServiceTest.java
back/src/test/java/org/pknu/weather/service/PostServiceTest.java

[BE/Refactor] 일부 API 수정

---

front/App.js
front/src/screens/LoginScreen.js

[FE/Feat] 일반 로그인, 회원가입 폼 추가

---

back/src/main/java/org/pknu/weather/controller/MainPageControllerV1.java
back/src/main/java/org/pknu/weather/domain/ExtraWeather.java
back/src/main/java/org/pknu/weather/dto/WeatherResponse.java
back/src/main/java/org/pknu/weather/feignClient/utils/ExtraWeatherApiUtils.java
back/src/main/java/org/pknu/weather/service/MainPageService.java
back/src/main/java/org/pknu/weather/service/WeatherService.java

- #192 
- 로케이션 Id를 쿼리 파라미터로 넘기면 해당 지역의 날씨정보를 전달하도록 수정합니다.

[BE/Feat] 로케이션 Id를 통해 원하는 지역의 날씨 정보를 얻을 수 있도록 수정

---

front/src/api/api.js
front/src/screens/LoginScreen.js

[FE/Fix] 테스터 계정 로그인 로직 수정

---

back/src/main/java/org/pknu/weather/aop/LocationCheckAspect.java
back/src/main/java/org/pknu/weather/controller/MainPageControllerV1.java

[BE/Fix] AOP 포인트컷 수정

---

front/ios/Podfile.lock
front/ios/Weather2.xcodeproj/project.pbxproj
front/ios/Weather2/Info.plist
front/ios/Weather2/Weather2.entitlements
front/package-lock.json
front/package.json
front/src/screens/LoginScreen.js
front/src/screens/RegisterProfileScreen.js

- Apple Developer에서 앱 생성 및 번들 ID 설정
- 애플 소셜 로그인 구현
- **위치 권한 거부 시 처리 로직 추가**
-

[FE/Feat] 애플 소셜 로그인 구현

---

front/src/screens/LoginScreen.js
front/src/screens/RegisterProfileScreen.js

[FE/Refactor] 테스트 계정 로그인 시 위치 등록 로직 추가

---

front/src/components/AirQuality.js
front/src/components/InterestItem.js
front/src/components/InterestPostScroll.js
front/src/components/PostScroll.js
front/src/components/Posts.js
front/src/screens/MyScreen.js

- 미세먼지 데이터 및 locationId 추가 예정
-

[FE/Feat] 취미탭 날씨 등급 설계

---

back/src/main/java/org/pknu/weather/dto/converter/PostResponseConverter.java
back/src/main/java/org/pknu/weather/repository/PostCustomRepositoryImpl.java
back/src/main/java/org/pknu/weather/service/PostQueryService.java

[BE/fix] 게시글 조회시 작성자가 올바르게 표시되도록 수정

---

front/android/app/build.gradle
front/src/api/api.js
front/src/components/InterestItem.js
front/src/components/Posts.js
front/src/components/WeatherInfoSlider.js

[FE/Fix] 취미탭 날씨 등급 설계 수정

---

front/src/api/api.js
front/src/components/CurrentLocationCommunity.js
front/src/components/HourlyForecast.js
front/src/components/InterestPostScroll.js
front/src/components/KakaoShareButton.js
front/src/components/PostScroll.js
front/src/components/Posts.js
front/src/components/ToggleViewButton.js
front/src/components/WeatherInfoSlider.js
front/src/screens/CommunityScreen.js
front/src/screens/HomeScreen.js
front/src/screens/PostCreationScreen.js

[FE/Refactor] Home탭 UI/UX 개선

---

front/android/app/build.gradle
front/src/components/InterestItem.js
front/src/screens/LoginScreen.js

[FE/Config] versionCode 업데이트

---

back/build.gradle
back/src/main/java/org/pknu/weather/domain/TagWeather.java
back/src/main/java/org/pknu/weather/dto/converter/TagWeatherConverter.java
back/src/main/java/org/pknu/weather/dto/converter/WeatherResponseConverter.java
back/src/main/java/org/pknu/weather/repository/PostCustomRepositoryImpl.java
back/src/main/java/org/pknu/weather/repository/TagWeatherRepository.java
back/src/main/java/org/pknu/weather/repository/WeatherCustomRepository.java
back/src/main/java/org/pknu/weather/repository/WeatherCustomRepositoryImpl.java
back/src/main/java/org/pknu/weather/service/PostService.java
back/src/main/resources/application.yml
back/src/test/java/org/pknu/weather/service/PostServiceTest.java

[BE/Feat] 테이블 추가 & 일부 로직 수정

---

front/src/components/HourlyForecast.js
front/src/components/WeatherHeader.js
front/src/components/WeatherHeaderCommunity.js

- 현재 시간을 기준으로 과거 시간 데이터를 포함하도록 조건 개선
- 흐린 날씨 및 강수 여부에 따른 배경색 반영 및 실시간 업데이트
-

[FE/Refactor] 헤더 동적 배경색 설정 로직 개선

---

back/src/main/java/org/pknu/weather/common/formatter/DateTimeFormatter.java

[BE/Fix] LocalDate 형태에서 Time과 관련된 메서드 호출 코드 수정

---

back/src/main/java/org/pknu/weather/domain/Weather.java
back/src/main/java/org/pknu/weather/dto/WeatherResponse.java
back/src/main/java/org/pknu/weather/dto/converter/WeatherResponseConverter.java

[BE/Fix] 응답에 체감온도를 포함하도록 수정

---

back/src/main/java/org/pknu/weather/controller/MainPageControllerV1.java
back/src/main/java/org/pknu/weather/repository/PostCustomRepository.java
back/src/main/java/org/pknu/weather/repository/PostCustomRepositoryImpl.java
back/src/main/java/org/pknu/weather/service/MainPageService.java
back/src/main/java/org/pknu/weather/service/PostQueryService.java
back/src/test/java/org/pknu/weather/config/TestConfig.java
back/src/test/java/org/pknu/weather/repository/LocationRepositoryTest.java
back/src/test/java/org/pknu/weather/repository/PostCustomRepositoryTest.java
back/src/test/java/org/pknu/weather/repository/PostRepositoryTest.java
back/src/test/java/org/pknu/weather/repository/WeatherRepositoryTest.java

[BE/Refactor] #236

---

front/App.js
front/ios/Podfile.lock
front/package-lock.json
front/package.json
front/src/components/AirQuality.js
front/src/components/HourlyForecast.js
front/src/components/PostScroll.js
front/src/components/Posts.js
front/src/components/WeatherGraph.js
front/src/components/WeatherHeader.js
front/src/components/WeatherHeaderCommunity.js
front/src/screens/CommunityScreen.js
front/src/screens/HomeScreen.js
front/src/screens/LoginScreen.js
front/src/screens/TermsAgreementScreen.js

- 약관 동의를 위한 네이티브 체크박스 정상 렌더링
@react-native-community/checkbox 라이브러리 사용
-

[FE/Feat] 약관 동의 화면 구현

---

front/src/api/api.js
front/src/components/HourlyForecast.js
front/src/components/WeatherHeader.js
front/src/components/WeatherHeaderCommunity.js
front/src/screens/LoginScreen.js
front/src/screens/RegisterProfileScreen.js
front/src/screens/TermsAgreementScreen.js

[FE/Feat] 회원 정보 등록 API 호출 로직 추가

---

front/App.js
front/src/api/api.js
front/src/components/HourlyForecast.js
front/src/components/PostScroll.js
front/src/components/Posts.js
front/src/components/WeatherGraph.js
front/src/components/WeatherHeader.js
front/src/components/WeatherHeaderCommunity.js
front/src/screens/CommunityScreen.js
front/src/screens/HomeScreen.js
front/src/screens/LoginScreen.js
front/src/screens/MyScreen.js
front/src/screens/PostCreationScreen.js
front/src/screens/ProfileScreen.js
front/src/screens/RegisterProfileScreen.js
front/src/screens/TermsAgreementScreen.js
front/src/screens/TermsViewScreen.js

[FE/Feat] 약관 페이지 링크 추가 및 로그인 로직 통합

---

back/src/main/java/org/pknu/weather/domain/Member.java
back/src/test/java/org/pknu/weather/repository/PostCustomRepositoryTest.java

- #235 
- 회원 탈퇴시, 로케이션 엔티티를 삭제하지 않도록 수정

[BE/FIX] 회원과  로케이션 엔티티의 관계 수정

---

front/App.js
front/src/api/api.js
front/src/screens/MyScreen.js

[FE/Fix] 회원 탈퇴 로직 수정

---

front/src/components/KakaoShareButton.js
front/src/components/WeatherGraph.js
front/src/components/WeatherHeader.js
front/src/components/WeatherHeaderCommunity.js

- 그래프 세로축에 최고/최저 온도를 표시하도록 수정
- 레이아웃 최적화
-

[FE/Refcator] 날씨 그래프 레이아웃 개선

---

back/src/main/java/org/pknu/weather/filter/TokenCheckFilter.java

- #268 
-  토큰 체크 필터 실행시 토큰 체크 필터의 실행 여부를 나타내는 로그의 레벨을 info에서 debug로 수정

[BE/Refactor] 토큰 체크 필터의 로그 레벨 변경

---

back/src/main/java/org/pknu/weather/controller/MemberControllerV1.java
back/src/main/java/org/pknu/weather/service/MemberService.java
back/src/test/java/org/pknu/weather/controller/MemberControllerV1Test.java

[BE/Refactor] 약관동의 로직 분리

---

front/App.js
front/src/api/api.js
front/src/components/WeatherHeader.js
front/src/screens/HomeScreen.js
front/src/screens/LoginScreen.js
front/src/screens/MyScreen.js
front/src/screens/PostCreationScreen.js
front/src/screens/RegisterProfileScreen.js
front/src/screens/TermsAgreementScreen.js

[FE/Fix] 회원가입 시 이탈 예외 처리 추가

---

front/App.js
front/src/api/api.js
front/src/screens/RegisterProfileScreen.js

[FE/Fix] 회원가입 시 스택 전환 로직 수정

---

back/src/main/java/org/pknu/weather/config/FilterConfig.java
back/src/main/java/org/pknu/weather/controller/HealthCheckController.java
back/src/main/java/org/pknu/weather/filter/InitFilter.java

[BE/Fix] 필터 추가, health 체크용 컨트롤러 추가

---

front/android/app/build.gradle

[FE/Refactor] 버전 코드 업데이트

---

front/src/components/WeatherHeader.js
front/src/screens/ProfileScreen.js
front/src/screens/RegisterProfileScreen.js
front/src/screens/TestLoginScreen.js

[FE/Fix] 위치 권한 허용 요청 및 로직 개선

---

front/App.js
front/ios/Weather2.xcodeproj/project.pbxproj
front/src/components/WeatherHeader.js
front/src/contexts/RefreshContext.js
front/src/screens/CommunityScreen.js
front/src/screens/HomeScreen.js

- 위치 클릭 시 동작하도록 구현된 기능을 앱 실행 시 동작하도록 수정
-

[FE/Fix] 사용자 위치 설정 로직 수정

---

.github/workflows/gradle-dev.yml
.github/workflows/gradle-test.yml

[BE/Ci] 개발서버 배포 워크플로 적용이 안돼서 수정

---

front/src/api/api.js
front/src/components/PostScroll.js
front/src/components/Posts.js
front/src/components/WeatherHeader.js
front/src/screens/HomeScreen.js

[FE/Refactor] 예외 처리 개선 및 요청 서버 변경

---

README.md
front/src/api/api.js
front/src/components/PostScroll.js
front/src/components/Posts.js
front/src/components/WeatherHeader.js
front/src/screens/HomeScreen.js

[FE/Refactor] 요청 서버 변경사항 반영

---

front/android/app/build.gradle
front/android/app/src/main/AndroidManifest.xml
front/android/app/src/main/res/values/strings.xml
front/ios/Weather2.xcodeproj/project.pbxproj
front/ios/Weather2/Info.plist
front/src/components/WeatherHeader.js
front/src/screens/LoginScreen.js
front/src/screens/RegisterProfileScreen.js

[FE/Fix] 위치 접근 권한 안내 수정

---

front/android/app/src/main/AndroidManifest.xml
front/ios/Weather2/Info.plist
front/src/components/WeatherGraph.js
front/src/screens/LoginScreen.js

[FE/Fix] UI 깨짐 방지 및 그래프 개선

---

back/src/main/java/org/pknu/weather/feignClient/dto/AirConditionResponseDTO.java
back/src/main/java/org/pknu/weather/feignClient/utils/ExtraWeatherApiUtils.java

- #344 
- 공공 api에서 정상적인 미세먼지 값을 전송하지 않은 경우 처리

bug: 미세 먼지 수치의 정상적인 숫자 값을 못 받은 경우 처리

---

back/src/main/java/org/pknu/weather/feignClient/dto/AirConditionResponseDTO.java
back/src/main/java/org/pknu/weather/feignClient/utils/ExtraWeatherApiUtils.java
back/src/main/java/org/pknu/weather/repository/MemberRepository.java
back/src/main/java/org/pknu/weather/service/WeatherService.java

Release -> main

---

back/src/main/java/org/pknu/weather/feignClient/WeatherFeignClient.java
back/src/main/java/org/pknu/weather/feignClient/config/FeignClientConfig.java
back/src/main/java/org/pknu/weather/feignClient/error/CommonErrorDecoder.java
back/src/main/java/org/pknu/weather/feignClient/error/WeatherFeignErrorDecoder.java
back/src/main/java/org/pknu/weather/security/exception/WeatherFeignClientException.java
back/src/main/resources/application.yml
back/src/test/java/org/pknu/weather/feignClient/WeatherFeignClientTest.java
back/src/test/resources/application.yml

- 공공데이터 API 에러 발생시 간헐적으로 xml 응답이 오는것을 해결하기 위해 ErrorDecoder 를 설정합니다. 
-

Release -> dev

---

back/src/main/java/org/pknu/weather/feignClient/utils/ExtraWeatherApiUtils.java

bug: 커넥션 풀 최적화

---

back/src/main/java/org/pknu/weather/feignClient/utils/ExtraWeatherApiUtils.java

- #365 
- 2025년 4월 24일 이후에는 iOS 18 SDK로 빌드해야하므로 Xcode 16으로 업데이트가 필요하다
-

Release-> Dev

---

back/src/main/java/org/pknu/weather/repository/WeatherCustomRepositoryImpl.java

[BE/Fix] 예보 데이터가 제대로 갱신되지 않는 현상 수정

---

.github/workflows/gradle-dev-ci.yml
back/src/main/java/org/pknu/weather/aop/util/LoggingUtils.java

[BE/Refactor] 개발서버에서  예외처리된 예외는 세부 내용을 로깅하지 않도록 변경

---

back/src/main/java/org/pknu/weather/apiPayload/code/status/ErrorStatus.java
back/src/main/java/org/pknu/weather/repository/WeatherCustomRepositoryImpl.java
back/src/main/java/org/pknu/weather/service/WeatherWriteService.java

[BE/Refactor] NPE 예외 처리

---

back/src/main/java/org/pknu/weather/aop/IntegrationLoggingAspect.java
back/src/main/java/org/pknu/weather/aop/Pointcuts.java
back/src/main/java/org/pknu/weather/aop/util/LoggingUtils.java

[BE] 개발 서버 로그를 스레드 단위로 기록하도록 수정합니다

---

back/src/main/java/org/pknu/weather/aop/IntegrationLoggingAspect.java
back/src/main/java/org/pknu/weather/aop/Pointcuts.java
back/src/main/java/org/pknu/weather/aop/util/LoggingUtils.java
back/src/main/java/org/pknu/weather/feignClient/utils/WeatherFeignClientUtils.java

[BE] 단기 예보 API 오류 발생으로 로그 추가

---

back/src/main/java/org/pknu/weather/service/MainPageService.java
back/src/main/java/org/pknu/weather/service/WeatherService.java
back/src/main/java/org/pknu/weather/service/WeatherWriteService.java
back/src/main/resources/application.yml

[BE/Fix] 커넥션 누수 지점 찾는 중

---

front/android/app/src/main/AndroidManifest.xml
front/android/app/src/main/res/values/colors.xml

`ex. Closes #378 `
Closes #
- FCM 토큰 발급 및 토큰 변경 감지 로직 추가
- 안드로이드 알림 아이콘 변경 사항 반영은 미정

[FE/Feat] FCM 토큰 변경 감지 기능 구현

---

back/src/main/java/org/pknu/weather/aop/PreventDuplicateAspect.java
back/src/main/java/org/pknu/weather/apiPayload/code/status/ErrorStatus.java
back/src/main/java/org/pknu/weather/config/CacheConfig.java

[BE/refactor] 연속 입력 방지 AOP 코드 작성

---

back/src/main/java/org/pknu/weather/aop/PreventDuplicateAspect.java
back/src/main/java/org/pknu/weather/aop/util/LoggingUtils.java
back/src/main/java/org/pknu/weather/apiPayload/code/status/ErrorStatus.java
back/src/main/java/org/pknu/weather/config/CacheConfig.java
back/src/main/java/org/pknu/weather/controller/MainPageControllerV1.java
back/src/main/java/org/pknu/weather/controller/MemberControllerV1.java
back/src/main/java/org/pknu/weather/domain/Member.java
back/src/main/java/org/pknu/weather/dto/MemberResponse.java
back/src/main/java/org/pknu/weather/dto/converter/MemberResponseConverter.java
back/src/main/java/org/pknu/weather/dto/converter/WeatherResponseConverter.java
back/src/main/java/org/pknu/weather/repository/PostRepository.java
back/src/main/java/org/pknu/weather/service/MemberService.java
back/src/main/java/org/pknu/weather/service/RecommendationService.java
back/src/main/java/org/pknu/weather/service/WeatherQueryService.java
back/src/test/java/org/pknu/weather/repository/MemberRepositoryTest.java
back/src/test/java/org/pknu/weather/service/ExpRewardServiceTest.java
back/src/test/java/org/pknu/weather/service/WeatherQueryServiceTest.java

`ex. Closes #123`
Closes #
- 본인이 작성한 글에 좋아요를 눌렀을 때 반응하지 않던 현상 수정
- 레벨업 로직 변경
- 마이페이지 접속시 호출 할 수 있는 레벨업 확인 API 생성

[BE/Fix] 추천 및 레벨업 관련 수정

---

back/src/main/java/org/pknu/weather/config/AsyncConfig.java
back/src/main/java/org/pknu/weather/controller/ExpRewardControllerV1.java
back/src/main/java/org/pknu/weather/event/AbstractExpEvent.java
back/src/main/java/org/pknu/weather/event/AttendanceCheckedEvent.java
back/src/main/java/org/pknu/weather/event/ExpRewardListener.java
back/src/main/java/org/pknu/weather/event/PostCreatedEvent.java
back/src/main/java/org/pknu/weather/event/RecommendEvent.java
back/src/main/java/org/pknu/weather/event/RecommendedEvent.java
back/src/main/java/org/pknu/weather/service/AttendanceService.java
back/src/main/java/org/pknu/weather/service/PostService.java
back/src/main/java/org/pknu/weather/service/RecommendationService.java
back/src/test/java/org/pknu/weather/common/TestDataCreator.java
back/src/test/java/org/pknu/weather/controller/CommunityControllerV1Test.java
back/src/test/java/org/pknu/weather/service/PostServiceUnitTest.java

`ex. Closes #123`
Closes #410 
- 추가적으로 비동기 메서드가 모든 커넥션을 점유하지 않도록 최대 커넥션 수를 조절합니다.

[BE/Refactor] 경험치 증가 로직 이벤트 방식으로 변경

---

.github/workflows/gradle-dev-ci.yml

`ex. Closes #123`
Closes #
- CI 설정 중 오타를 수정했습니다.

[BE/fix]: CI 설정 오타 수정

---

back/src/main/java/org/pknu/weather/controller/AlarmControllerV2.java
back/src/main/java/org/pknu/weather/domain/Alarm.java
back/src/main/java/org/pknu/weather/domain/common/AlarmType.java
back/src/main/java/org/pknu/weather/repository/AlarmRepository.java
back/src/main/java/org/pknu/weather/service/AlarmService.java
back/src/main/java/org/pknu/weather/service/handler/TestWeatherSummaryAlarmHandler.java
back/src/test/java/org/pknu/weather/integration/AlarmCrudTest.java
back/src/test/java/org/pknu/weather/integration/AlarmSendTest.java
back/src/test/java/org/pknu/weather/service/AlarmServiceTest.java

[BE/Fix]: 한 기기에서 여러 명이 로그인 할 경우를 고려해 수정

---

back/src/main/java/org/pknu/weather/service/WeatherService.java

[BE/Refactor] 날씨 데이터 업데이트 로직 수정

---

back/src/main/java/org/pknu/weather/service/message/WeatherAlarmMessageBuilder.java
back/src/main/java/org/pknu/weather/service/sender/FcmNotificationSender.java
back/src/test/java/org/pknu/weather/service/message/WeatherAlarmMessageBuilderTest.java

`ex. Closes #123`
Closes 
- 알람 전송 형식을 수정했습니다.
- ios환경에서 알람 배지를 삭제했습니다.

[BE/Fix] 알람 전송 형식 수정 및 알람 배지 삭제

---

back/src/main/resources/application.yml

[BE/Fix] s3 버킷명 변경으로 인한 수정
